---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver:
      require_chef_omnibus: 12.3
      vagrantfile_erb: Vagrantfile.erb
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
      - ["forwarded_port", {guest: 80, host: 80}]
      - ["forwarded_port", {guest: 443, host: 443}]

suites:
  - name: default
    run_list:
      - recipe[guacamole::default]
    attributes:
